# Generated by Django 3.2.18 on 2023-03-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FutureTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="task ID"
                    ),
                ),
                (
                    "eta",
                    models.DateTimeField(
                        help_text="The date and time when the task should be executed",
                        verbose_name="ETA",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Various execution data"
                    ),
                ),
                ("type", models.CharField(max_length=255, verbose_name="Task type")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Status open"),
                            ("in_progress", "Status in progress"),
                            ("done", "Status done"),
                            ("error", "Status error"),
                        ],
                        default="open",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                (
                    "result",
                    models.JSONField(blank=True, null=True, verbose_name="Result"),
                ),
            ],
        ),
    ]
