# Generated by Django 3.2.22 on 2023-10-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_future_tasks", "0002_periodic_future_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="futuretask",
            name="execution_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
