# Generated by Django 3.2.22 on 2023-10-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_future_tasks", "0003_futuretask_execution_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futuretask",
            name="execution_time",
            field=models.FloatField(blank=True, help_text="in seconds", null=True),
        ),
        migrations.AlterField(
            model_name="futuretask",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Status open"),
                    ("in_progress", "Status in progress"),
                    ("interrupted", "Status interrupted"),
                    ("done", "Status done"),
                    ("error", "Status error"),
                ],
                default="open",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
