# Generated by Django 3.2.22 on 2023-10-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_future_tasks", "0004_futuretask_status_interrupted"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodicfuturetask",
            name="max_number_of_executions",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Maximal number of executions"
            ),
        ),
    ]
