# Generated by Django 3.2.22 on 2023-10-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_future_tasks", "0005_periodicfuturetask_max_number_of_executions"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodicfuturetask",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Executions until"
            ),
        ),
        migrations.AddConstraint(
            model_name="periodicfuturetask",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_time__isnull", True),
                    ("max_number_of_executions__isnull", True),
                    _connector="OR",
                ),
                name="not_both_not_null",
            ),
        ),
    ]
