# Generated by Django 4.2.14 on 2024-07-22 11:43

from django.db import migrations

import django_future_tasks.fields


class Migration(migrations.Migration):
    dependencies = [
        ("django_future_tasks", "0006_periodicfuturetask_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodicfuturetask",
            name="cron_string",
            field=django_future_tasks.fields.FutureTaskCronField(
                default="* * * * * *",
                help_text="Minute Hour Day Month Weekday Second",
                max_length=100,
            ),
        ),
    ]
