# Generated by Django 3.2.24 on 2024-02-29 15:34

from django.db import migrations

import django_future_tasks.fields


class Migration(migrations.Migration):
    dependencies = [
        ("django_future_tasks", "0006_periodicfuturetask_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodicfuturetask",
            name="cron_string",
            field=django_future_tasks.fields.FuturetaskCronField(
                default="* * * * *",
                help_text="Minute Hour Day Month Weekday",
                max_length=100,
            ),
        ),
    ]
