name: Run linter and tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
        django-version:
          - '3.2'
          - '4.1'
          - '4.2'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install django~=${{ matrix.django-version }}.0

      - name: Run lint and code review with isort and black
        run: |
          pre-commit run --all-files
      - name: Run tests with coverage
        run: |
          # prepare Django project: link all necessary data from the test project into the root directory
          # Hint: Simply changing the directory does not work (leads to missing files in coverage report)
          ln -s ./tests/core core
          ln -s ./tests/testapp testapp
          ln -s ./tests/manage.py manage.py
          # run tests with coverage
          coverage run \
            --source='./django_future_tasks' \
            manage.py test
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3